import {
  User,
  Campaign,
  Phase,
  Milestone,
  WorkPackage,
  SocialMediaAccount,
  SocialMediaPost,
  MediaFile,
  Agent,
  Workflow,
  Participant,
  ChatMessage,
  Credential,
} from "../types";
import demoMediaImage from "../assets/hero.png";

const demoTextFile =
  "data:text/plain;charset=utf-8," +
  encodeURIComponent(
    "CampaignHub Demo-Dokument\n\nDiese lokale Beispieldatei kann in der Mediathek angesehen und heruntergeladen werden.",
  );
const demoEmptyZip =
  "data:application/zip;base64,UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@example.com",
    name: "Admin User",
    role: "Admin",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    email: "worker@example.com",
    name: "Worker User",
    role: "Worker",
    campaignRole: "Content Creator",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date(),
  },
  {
    id: "3",
    email: "visitor@example.com",
    name: "Visitor User",
    role: "Visitor",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date(),
  },
  {
    id: "4",
    email: "agent@example.com",
    name: "Agent User",
    role: "Agent",
    campaignRole: "AI Assistant",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date(),
  },
];

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: "c1",
    name: "Autumn Product Launch 2026",
    description: "Launch campaign for our new product line in autumn 2026",
    status: "active",
    startDate: new Date("2026-07-15"),
    endDate: new Date("2026-10-31"),
    createdAt: new Date("2026-06-15"),
    updatedAt: new Date(),
  },
  {
    id: "c2",
    name: "Holiday Social Media Blitz",
    description: "Intensive social media campaign for the holiday season",
    status: "planning",
    startDate: new Date("2026-10-01"),
    endDate: new Date("2026-12-15"),
    createdAt: new Date("2026-07-01"),
    updatedAt: new Date(),
  },
  {
    id: "c3",
    name: "Brand Awareness Q3",
    description: "Increase brand awareness through targeted content",
    status: "active",
    startDate: new Date("2026-08-01"),
    endDate: new Date("2026-09-30"),
    createdAt: new Date("2026-07-01"),
    updatedAt: new Date(),
  },
];

// Mock Phases
export const mockPhases: Phase[] = [
  {
    id: "p1",
    campaignId: "c1",
    name: "Pre-Launch Teaser",
    description: "Build anticipation with teaser content",
    startDate: new Date("2026-07-15"),
    endDate: new Date("2026-07-31"),
    status: "completed",
    order: 1,
  },
  {
    id: "p2",
    campaignId: "c1",
    name: "Launch Week",
    description: "Main product launch activities",
    startDate: new Date("2026-08-01"),
    endDate: new Date("2026-08-20"),
    status: "current",
    order: 2,
  },
  {
    id: "p3",
    campaignId: "c1",
    name: "Post-Launch Engagement",
    description: "Maintain momentum after launch",
    startDate: new Date("2026-08-21"),
    endDate: new Date("2026-09-15"),
    status: "upcoming",
    order: 3,
  },
  {
    id: "p4",
    campaignId: "c3",
    name: "Content Creation",
    description: "Create and schedule brand content",
    startDate: new Date("2026-08-01"),
    endDate: new Date("2026-08-31"),
    status: "current",
    order: 1,
  },
];

// Mock Milestones
export const mockMilestones: Milestone[] = [
  {
    id: "m1",
    phaseId: "p1",
    name: "Teaser Video Published",
    description: "Release first teaser video on all platforms",
    dueDate: new Date("2026-07-20"),
    status: "completed",
    order: 1,
  },
  {
    id: "m2",
    phaseId: "p1",
    name: "Influencer Outreach Complete",
    description: "Contact and confirm partnerships with influencers",
    dueDate: new Date("2026-07-28"),
    status: "completed",
    order: 2,
  },
  {
    id: "m3",
    phaseId: "p2",
    name: "Launch Event Live Stream",
    description: "Host live stream launch event",
    dueDate: new Date("2026-08-18"),
    status: "in_progress",
    order: 1,
  },
  {
    id: "m4",
    phaseId: "p2",
    name: "Press Release Distribution",
    description: "Distribute press release to media outlets",
    dueDate: new Date("2026-08-20"),
    status: "pending",
    order: 2,
  },
  {
    id: "m5",
    phaseId: "p4",
    name: "Content Calendar Finalized",
    description: "Complete content calendar for Q3",
    dueDate: new Date("2026-08-25"),
    status: "in_progress",
    order: 1,
  },
];

// Mock Work Packages
export const mockWorkPackages: WorkPackage[] = [
  {
    id: "wp1",
    milestoneId: "m1",
    title: "Create teaser video script",
    description: "Write engaging script for 30-second teaser video",
    status: "finished",
    assigneeId: "2",
    assigneeType: "user",
    priority: "high",
    dueDate: new Date("2026-07-18"),
    estimatedHours: 8,
    actualHours: 7,
    createdAt: new Date("2026-07-10"),
    updatedAt: new Date("2026-07-18"),
  },
  {
    id: "wp2",
    milestoneId: "m1",
    title: "Film and edit teaser video",
    description: "Production of teaser video content",
    status: "finished",
    assigneeId: "2",
    assigneeType: "user",
    priority: "high",
    dueDate: new Date("2026-07-25"),
    estimatedHours: 16,
    actualHours: 18,
    createdAt: new Date("2026-07-10"),
    updatedAt: new Date("2026-07-25"),
  },
  {
    id: "wp3",
    milestoneId: "m3",
    title: "Set up live stream infrastructure",
    description: "Configure streaming software and test connections",
    status: "in_progress",
    assigneeId: "2",
    assigneeType: "user",
    priority: "critical",
    dueDate: new Date("2026-08-17"),
    estimatedHours: 12,
    createdAt: new Date("2026-08-05"),
    updatedAt: new Date(),
  },
  {
    id: "wp4",
    milestoneId: "m3",
    title: "Prepare launch event presentation",
    description: "Create slides and talking points for launch event",
    status: "in_progress",
    assigneeId: "a1",
    assigneeType: "agent",
    priority: "high",
    dueDate: new Date("2026-08-16"),
    estimatedHours: 10,
    createdAt: new Date("2026-08-04"),
    updatedAt: new Date(),
  },
  {
    id: "wp5",
    milestoneId: "m4",
    title: "Draft press release",
    description: "Write compelling press release for product launch",
    status: "planned",
    assigneeId: "a1",
    assigneeType: "agent",
    priority: "high",
    dueDate: new Date("2026-08-19"),
    estimatedHours: 4,
    createdAt: new Date("2026-08-08"),
    updatedAt: new Date(),
  },
  {
    id: "wp6",
    milestoneId: "m5",
    title: "Research trending topics",
    description: "Analyze current trends for content inspiration",
    status: "blocker",
    assigneeId: "2",
    assigneeType: "user",
    priority: "medium",
    dueDate: new Date("2026-08-25"),
    estimatedHours: 6,
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date(),
  },
  {
    id: "wp7",
    milestoneId: "m5",
    title: "Design visual assets",
    description: "Create graphics and templates for social posts",
    status: "planned",
    assigneeId: "2",
    assigneeType: "user",
    priority: "medium",
    dueDate: new Date("2026-08-28"),
    estimatedHours: 20,
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date(),
  },
];

// Mock Social Media Accounts
export const mockSocialMediaAccounts: SocialMediaAccount[] = [
  {
    id: "sm1",
    platform: "Instagram",
    name: "@brand_official",
    email: "social@brand.com",
    url: "https://instagram.com/brand_official",
    apiEndpoint: "https://graph.instagram.com",
    connectionStatus: "connected",
    isActive: true,
    campaignIds: ["c1", "c3"],
    lastSyncedAt: new Date(),
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date(),
  },
  {
    id: "sm2",
    platform: "Twitter/X",
    name: "@BrandOfficial",
    email: "social@brand.com",
    url: "https://twitter.com/BrandOfficial",
    apiEndpoint: "https://api.twitter.com/2",
    connectionStatus: "connected",
    isActive: true,
    campaignIds: ["c1", "c2", "c3"],
    lastSyncedAt: new Date(),
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date(),
  },
  {
    id: "sm3",
    platform: "LinkedIn",
    name: "Brand Company",
    email: "linkedin@brand.com",
    url: "https://linkedin.com/company/brand",
    apiEndpoint: "https://api.linkedin.com/v2",
    connectionStatus: "connected",
    isActive: true,
    campaignIds: ["c1", "c3"],
    lastSyncedAt: new Date(),
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date(),
  },
  {
    id: "sm4",
    platform: "TikTok",
    name: "@brand_tiktok",
    email: "tiktok@brand.com",
    url: "https://tiktok.com/@brand_tiktok",
    apiEndpoint: "https://open.tiktokapis.com",
    connectionStatus: "connected",
    isActive: true,
    campaignIds: ["c2"],
    lastSyncedAt: new Date(),
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date(),
  },
  {
    id: "sm5",
    platform: "Facebook",
    name: "Brand Official Page",
    email: "facebook@brand.com",
    url: "https://facebook.com/brandofficial",
    apiEndpoint: "https://graph.facebook.com",
    connectionStatus: "disconnected",
    isActive: false,
    campaignIds: [],
    lastSyncedAt: new Date("2025-03-01"),
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-03-01"),
  },
];

// Mock Social Media Posts
export const mockSocialMediaPosts: SocialMediaPost[] = [
  {
    id: "post1",
    accountId: "sm1",
    platform: "Instagram",
    content:
      "🚀 Something amazing is coming! Stay tuned for our biggest announcement yet. #ComingSoon #NewProduct",
    mediaUrls: [demoMediaImage],
    postedAt: new Date("2026-08-05T10:00:00"),
    likes: 1247,
    shares: 89,
    comments: 156,
    engagement: 12.5,
  },
  {
    id: "post2",
    accountId: "sm2",
    platform: "Twitter/X",
    content:
      "The wait is almost over! Our team has been working hard to bring you something special. Launch day: August 18th! 🎉",
    postedAt: new Date("2026-08-08T14:30:00"),
    likes: 892,
    shares: 234,
    comments: 67,
    engagement: 8.9,
  },
  {
    id: "post3",
    accountId: "sm3",
    platform: "LinkedIn",
    content:
      "We're excited to announce our upcoming product launch! This represents months of innovation and dedication from our incredible team. Learn more at our launch event on August 18th.",
    mediaUrls: [demoMediaImage],
    postedAt: new Date("2026-08-09T09:00:00"),
    likes: 456,
    shares: 78,
    comments: 34,
    engagement: 5.2,
  },
  {
    id: "post4",
    accountId: "sm1",
    platform: "Instagram",
    content:
      "Behind the scenes: Our creative team putting the finishing touches on the launch campaign ✨ #BTS #TeamWork",
    mediaUrls: [demoMediaImage],
    postedAt: new Date("2026-08-10T16:00:00"),
    likes: 2103,
    shares: 145,
    comments: 289,
    engagement: 18.7,
  },
  {
    id: "post5",
    accountId: "sm2",
    platform: "Twitter/X",
    content: "3 days until launch! Who's ready? Drop a 🙋 if you're excited!",
    postedAt: new Date("2026-08-11T11:00:00"),
    likes: 1567,
    shares: 412,
    comments: 523,
    engagement: 22.1,
  },
  {
    id: "post6",
    accountId: "sm4",
    platform: "TikTok",
    content:
      "POV: You're about to witness the launch of the year 👀 #FYP #ProductLaunch",
    mediaUrls: [demoMediaImage],
    postedAt: new Date("2026-08-12T18:00:00"),
    likes: 45678,
    shares: 3421,
    comments: 1876,
    engagement: 35.4,
  },
];

// Demo media deliberately uses local/data URLs so previews and downloads work
// without a storage backend.
export const mockMediaFiles: MediaFile[] = [
  {
    id: "mf1",
    filename: "campaign_teaser_storyboard.png",
    originalName: "campaign_teaser_storyboard.png",
    mimeType: "image/png",
    size: 13312,
    url: demoMediaImage,
    uploadedBy: "2",
    campaignId: "c1",
    tags: ["teaser", "video", "launch"],
    createdAt: new Date("2026-07-02"),
  },
  {
    id: "mf2",
    filename: "product_hero_image.png",
    originalName: "hero_shot_retouched.png",
    mimeType: "image/png",
    size: 13312,
    url: demoMediaImage,
    uploadedBy: "2",
    campaignId: "c1",
    tags: ["product", "hero", "image"],
    createdAt: new Date("2026-07-05"),
  },
  {
    id: "mf3",
    filename: "campaign_notes.txt",
    originalName: "CampaignHub_Demo_Notes.txt",
    mimeType: "text/plain",
    size: 113,
    url: demoTextFile,
    uploadedBy: "1",
    campaignId: "c1",
    tags: ["guidelines", "brand", "documentation"],
    createdAt: new Date("2026-06-15"),
  },
  {
    id: "mf4",
    filename: "social_templates.zip",
    originalName: "instagram_linkedin_templates.zip",
    mimeType: "application/zip",
    size: 22,
    url: demoEmptyZip,
    uploadedBy: "2",
    campaignId: "c3",
    tags: ["templates", "social", "design"],
    createdAt: new Date("2026-08-02"),
  },
];

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: "a1",
    name: "Content Generator",
    type: "llm-writer",
    description: "AI agent for generating social media content and copy",
    isActive: true,
    capabilities: ["content-writing", "hashtag-generation", "tone-adjustment"],
    configuration: {
      model: "gemma3",
      temperature: 0.7,
      maxTokens: 500,
    },
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "a2",
    name: "Analytics Reporter",
    type: "data-analyzer",
    description:
      "AI agent for analyzing social media metrics and generating reports",
    isActive: true,
    capabilities: ["data-analysis", "report-generation", "trend-detection"],
    configuration: {
      model: "gemma3",
      temperature: 0.3,
      maxTokens: 2000,
    },
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date(),
  },
  {
    id: "a3",
    name: "Engagement Bot",
    type: "interaction-manager",
    description: "AI agent for managing comments and engagement",
    isActive: false,
    capabilities: [
      "comment-response",
      "sentiment-analysis",
      "priority-flagging",
    ],
    configuration: {
      model: "gemma3",
      temperature: 0.5,
      maxTokens: 300,
    },
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date(),
  },
];

// Mock Workflows
export const mockWorkflows: Workflow[] = [
  {
    id: "w1",
    name: "Daily Content Posting",
    description: "Automated workflow for daily social media content posting",
    steps: [
      {
        id: "ws1",
        order: 1,
        action: "fetch-scheduled-content",
        parameters: { timeWindow: "24h" },
      },
      {
        id: "ws2",
        order: 2,
        action: "generate-hashtags",
        agentId: "a1",
        parameters: { count: 10, style: "trending" },
      },
      {
        id: "ws3",
        order: 3,
        action: "publish-to-platforms",
        parameters: { platforms: ["instagram", "twitter", "linkedin"] },
      },
    ],
    triggerType: "scheduled",
    schedule: "0 9 * * *", // Daily at 9 AM
    isActive: true,
    campaignId: "c1",
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date(),
  },
  {
    id: "w2",
    name: "Weekly Analytics Report",
    description: "Generate and distribute weekly performance reports",
    steps: [
      {
        id: "ws4",
        order: 1,
        action: "collect-metrics",
        parameters: {
          period: "7d",
          metrics: ["engagement", "reach", "followers"],
        },
      },
      {
        id: "ws5",
        order: 2,
        action: "analyze-trends",
        agentId: "a2",
        parameters: { compareWith: "previous_period" },
      },
      {
        id: "ws6",
        order: 3,
        action: "generate-report",
        agentId: "a2",
        parameters: { format: "pdf", includeCharts: true },
      },
      {
        id: "ws7",
        order: 4,
        action: "send-email",
        parameters: { recipients: ["team@brand.com"] },
      },
    ],
    triggerType: "scheduled",
    schedule: "0 8 * * 1", // Every Monday at 8 AM
    isActive: true,
    createdAt: new Date("2025-02-15"),
    updatedAt: new Date(),
  },
  {
    id: "w3",
    name: "Crisis Response Protocol",
    description: "Automated response workflow for negative sentiment detection",
    steps: [
      {
        id: "ws8",
        order: 1,
        action: "monitor-sentiment",
        parameters: {
          threshold: -0.5,
          keywords: ["complaint", "issue", "problem"],
        },
      },
      {
        id: "ws9",
        order: 2,
        action: "alert-team",
        condition: "previous.completed",
        parameters: { urgency: "high" },
      },
      {
        id: "ws10",
        order: 3,
        action: "draft-response",
        agentId: "a1",
        condition: "previous.completed",
        parameters: { tone: "empathetic", escalate: true },
      },
    ],
    triggerType: "event",
    isActive: true,
    campaignId: "c1",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date(),
  },
];

// Mock Participants
export const mockParticipants: Participant[] = [
  {
    id: "part1",
    userId: "1",
    name: "Admin User",
    email: "admin@example.com",
    role: "Campaign Manager",
    campaignIds: ["c1", "c2", "c3"],
  },
  {
    id: "part2",
    userId: "2",
    name: "Worker User",
    email: "worker@example.com",
    role: "Content Creator",
    campaignIds: ["c1", "c3"],
  },
  {
    id: "part3",
    agentId: "a1",
    name: "Content Generator",
    role: "AI Copywriter",
    campaignIds: ["c1", "c2", "c3"],
  },
  {
    id: "part4",
    agentId: "a2",
    name: "Analytics Reporter",
    role: "Data Analyst",
    campaignIds: ["c1", "c3"],
  },
  {
    id: "part5",
    userId: "3",
    name: "Visitor User",
    email: "visitor@example.com",
    role: "Stakeholder",
    campaignIds: ["c1", "c3"],
    status: "active",
  },
  {
    id: "part6",
    userId: "4",
    name: "Agent User",
    email: "agent@example.com",
    role: "AI Assistant",
    campaignIds: ["c1", "c2", "c3"],
    status: "active",
  },
  {
    id: "part7",
    agentId: "a3",
    name: "Engagement Bot",
    role: "Interaction Agent",
    campaignIds: [],
    status: "inactive",
  },
];

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg1",
    senderId: "1",
    senderName: "Admin User",
    content:
      "Welcome to the Autumn Product Launch campaign! Let's make this our best launch yet.",
    timestamp: new Date("2026-08-01T09:00:00"),
    isSystem: true,
  },
  {
    id: "msg2",
    senderId: "2",
    senderName: "Worker User",
    content: "Excited to get started! The teaser video is ready for review.",
    timestamp: new Date("2026-08-01T09:15:00"),
  },
  {
    id: "msg3",
    senderId: "a1",
    senderName: "Content Generator",
    content:
      "I've prepared 5 variations of launch day posts. Would you like to see them?",
    timestamp: new Date("2026-08-10T14:00:00"),
  },
  {
    id: "msg4",
    senderId: "2",
    senderName: "Worker User",
    content: "Yes please! Share them in the media library.",
    timestamp: new Date("2026-08-10T14:05:00"),
  },
];

// Mock Credentials
export const mockCredentials: Credential[] = [
  {
    id: "cred1",
    userId: "2",
    service: "Canva Pro",
    username: "designer@brand.com",
    notes: "Team account - shared access",
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "cred2",
    userId: "2",
    service: "Adobe Creative Cloud",
    username: "creative@brand.com",
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date(),
  },
  {
    id: "cred3",
    userId: "1",
    service: "Google Analytics",
    username: "analytics@brand.com",
    notes: "Master account for all properties",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-02-15"),
  },
];
