import { User, Campaign, Phase, Milestone, WorkPackage, SocialMediaAccount, SocialMediaPost, MediaFile, Agent, Workflow, Participant, ChatMessage, Credential, DashboardStats } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?u=admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    email: 'worker@example.com',
    name: 'Worker User',
    role: 'Worker',
    campaignRole: 'Content Creator',
    avatar: 'https://i.pravatar.cc/150?u=worker',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    email: 'visitor@example.com',
    name: 'Visitor User',
    role: 'Visitor',
    avatar: 'https://i.pravatar.cc/150?u=visitor',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    email: 'agent@example.com',
    name: 'Agent User',
    role: 'Agent',
    campaignRole: 'AI Assistant',
    avatar: 'https://i.pravatar.cc/150?u=agent',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date(),
  },
];

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Spring Product Launch 2025',
    description: 'Launch campaign for our new product line in spring 2025',
    status: 'active',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-05-31'),
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'c2',
    name: 'Summer Social Media Blitz',
    description: 'Intensive social media campaign for summer season',
    status: 'planning',
    startDate: new Date('2025-06-01'),
    endDate: new Date('2025-08-31'),
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'c3',
    name: 'Brand Awareness Q2',
    description: 'Increase brand awareness through targeted content',
    status: 'active',
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-06-30'),
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date(),
  },
];

// Mock Phases
export const mockPhases: Phase[] = [
  {
    id: 'p1',
    campaignId: 'c1',
    name: 'Pre-Launch Teaser',
    description: 'Build anticipation with teaser content',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-03-15'),
    status: 'completed',
    order: 1,
  },
  {
    id: 'p2',
    campaignId: 'c1',
    name: 'Launch Week',
    description: 'Main product launch activities',
    startDate: new Date('2025-03-16'),
    endDate: new Date('2025-03-23'),
    status: 'current',
    order: 2,
  },
  {
    id: 'p3',
    campaignId: 'c1',
    name: 'Post-Launch Engagement',
    description: 'Maintain momentum after launch',
    startDate: new Date('2025-03-24'),
    endDate: new Date('2025-04-15'),
    status: 'upcoming',
    order: 3,
  },
  {
    id: 'p4',
    campaignId: 'c3',
    name: 'Content Creation',
    description: 'Create and schedule brand content',
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-04-30'),
    status: 'current',
    order: 1,
  },
];

// Mock Milestones
export const mockMilestones: Milestone[] = [
  {
    id: 'm1',
    phaseId: 'p1',
    name: 'Teaser Video Published',
    description: 'Release first teaser video on all platforms',
    dueDate: new Date('2025-03-05'),
    status: 'completed',
    order: 1,
  },
  {
    id: 'm2',
    phaseId: 'p1',
    name: 'Influencer Outreach Complete',
    description: 'Contact and confirm partnerships with influencers',
    dueDate: new Date('2025-03-10'),
    status: 'completed',
    order: 2,
  },
  {
    id: 'm3',
    phaseId: 'p2',
    name: 'Launch Event Live Stream',
    description: 'Host live stream launch event',
    dueDate: new Date('2025-03-18'),
    status: 'in_progress',
    order: 1,
  },
  {
    id: 'm4',
    phaseId: 'p2',
    name: 'Press Release Distribution',
    description: 'Distribute press release to media outlets',
    dueDate: new Date('2025-03-20'),
    status: 'pending',
    order: 2,
  },
  {
    id: 'm5',
    phaseId: 'p4',
    name: 'Content Calendar Finalized',
    description: 'Complete content calendar for Q2',
    dueDate: new Date('2025-04-15'),
    status: 'in_progress',
    order: 1,
  },
];

// Mock Work Packages
export const mockWorkPackages: WorkPackage[] = [
  {
    id: 'wp1',
    milestoneId: 'm1',
    title: 'Create teaser video script',
    description: 'Write engaging script for 30-second teaser video',
    status: 'finished',
    assigneeId: '2',
    assigneeType: 'user',
    priority: 'high',
    dueDate: new Date('2025-03-01'),
    estimatedHours: 8,
    actualHours: 7,
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: 'wp2',
    milestoneId: 'm1',
    title: 'Film and edit teaser video',
    description: 'Production of teaser video content',
    status: 'finished',
    assigneeId: '2',
    assigneeType: 'user',
    priority: 'high',
    dueDate: new Date('2025-03-03'),
    estimatedHours: 16,
    actualHours: 18,
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-03'),
  },
  {
    id: 'wp3',
    milestoneId: 'm3',
    title: 'Set up live stream infrastructure',
    description: 'Configure streaming software and test connections',
    status: 'in_progress',
    assigneeId: '2',
    assigneeType: 'user',
    priority: 'critical',
    dueDate: new Date('2025-03-17'),
    estimatedHours: 12,
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date(),
  },
  {
    id: 'wp4',
    milestoneId: 'm3',
    title: 'Prepare launch event presentation',
    description: 'Create slides and talking points for launch event',
    status: 'in_progress',
    assigneeId: '4',
    assigneeType: 'agent',
    priority: 'high',
    dueDate: new Date('2025-03-16'),
    estimatedHours: 10,
    createdAt: new Date('2025-03-08'),
    updatedAt: new Date(),
  },
  {
    id: 'wp5',
    milestoneId: 'm4',
    title: 'Draft press release',
    description: 'Write compelling press release for product launch',
    status: 'planned',
    assigneeId: '4',
    assigneeType: 'agent',
    priority: 'high',
    dueDate: new Date('2025-03-18'),
    estimatedHours: 4,
    createdAt: new Date('2025-03-12'),
    updatedAt: new Date(),
  },
  {
    id: 'wp6',
    milestoneId: 'm5',
    title: 'Research trending topics',
    description: 'Analyze current trends for content inspiration',
    status: 'blocker',
    assigneeId: '2',
    assigneeType: 'user',
    priority: 'medium',
    dueDate: new Date('2025-04-10'),
    estimatedHours: 6,
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date(),
  },
  {
    id: 'wp7',
    milestoneId: 'm5',
    title: 'Design visual assets',
    description: 'Create graphics and templates for social posts',
    status: 'planned',
    assigneeId: '2',
    assigneeType: 'user',
    priority: 'medium',
    dueDate: new Date('2025-04-12'),
    estimatedHours: 20,
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date(),
  },
];

// Mock Social Media Accounts
export const mockSocialMediaAccounts: SocialMediaAccount[] = [
  {
    id: 'sm1',
    platform: 'Instagram',
    name: '@brand_official',
    email: 'social@brand.com',
    url: 'https://instagram.com/brand_official',
    token: 'ig_token_xxx',
    apiEndpoint: 'https://graph.instagram.com',
    isActive: true,
    campaignIds: ['c1', 'c3'],
    lastSyncedAt: new Date(),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'sm2',
    platform: 'Twitter/X',
    name: '@BrandOfficial',
    email: 'social@brand.com',
    url: 'https://twitter.com/BrandOfficial',
    token: 'tw_token_xxx',
    apiEndpoint: 'https://api.twitter.com/2',
    isActive: true,
    campaignIds: ['c1', 'c2', 'c3'],
    lastSyncedAt: new Date(),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'sm3',
    platform: 'LinkedIn',
    name: 'Brand Company',
    email: 'linkedin@brand.com',
    url: 'https://linkedin.com/company/brand',
    token: 'li_token_xxx',
    apiEndpoint: 'https://api.linkedin.com/v2',
    isActive: true,
    campaignIds: ['c1', 'c3'],
    lastSyncedAt: new Date(),
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date(),
  },
  {
    id: 'sm4',
    platform: 'TikTok',
    name: '@brand_tiktok',
    email: 'tiktok@brand.com',
    url: 'https://tiktok.com/@brand_tiktok',
    token: 'tt_token_xxx',
    apiEndpoint: 'https://open.tiktokapis.com',
    isActive: true,
    campaignIds: ['c2'],
    lastSyncedAt: new Date(),
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date(),
  },
  {
    id: 'sm5',
    platform: 'Facebook',
    name: 'Brand Official Page',
    email: 'facebook@brand.com',
    url: 'https://facebook.com/brandofficial',
    token: 'fb_token_xxx',
    apiEndpoint: 'https://graph.facebook.com',
    isActive: false,
    campaignIds: [],
    lastSyncedAt: new Date('2025-03-01'),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2025-03-01'),
  },
];

// Mock Social Media Posts
export const mockSocialMediaPosts: SocialMediaPost[] = [
  {
    id: 'post1',
    accountId: 'sm1',
    platform: 'Instagram',
    content: '🚀 Something amazing is coming! Stay tuned for our biggest announcement yet. #ComingSoon #NewProduct',
    mediaUrls: ['https://picsum.photos/seed/teaser1/600/600'],
    postedAt: new Date('2025-03-05T10:00:00'),
    likes: 1247,
    shares: 89,
    comments: 156,
    engagement: 12.5,
  },
  {
    id: 'post2',
    accountId: 'sm2',
    platform: 'Twitter/X',
    content: 'The wait is almost over! Our team has been working hard to bring you something special. Launch day: March 18th! 🎉',
    postedAt: new Date('2025-03-10T14:30:00'),
    likes: 892,
    shares: 234,
    comments: 67,
    engagement: 8.9,
  },
  {
    id: 'post3',
    accountId: 'sm3',
    platform: 'LinkedIn',
    content: 'We\'re excited to announce our upcoming product launch! This represents months of innovation and dedication from our incredible team. Learn more at our launch event on March 18th.',
    mediaUrls: ['https://picsum.photos/seed/professional/1200/630'],
    postedAt: new Date('2025-03-12T09:00:00'),
    likes: 456,
    shares: 78,
    comments: 34,
    engagement: 5.2,
  },
  {
    id: 'post4',
    accountId: 'sm1',
    platform: 'Instagram',
    content: 'Behind the scenes: Our creative team putting the finishing touches on the launch campaign ✨ #BTS #TeamWork',
    mediaUrls: ['https://picsum.photos/seed/bts1/600/600', 'https://picsum.photos/seed/bts2/600/600'],
    postedAt: new Date('2025-03-14T16:00:00'),
    likes: 2103,
    shares: 145,
    comments: 289,
    engagement: 18.7,
  },
  {
    id: 'post5',
    accountId: 'sm2',
    platform: 'Twitter/X',
    content: '3 days until launch! Who\'s ready? Drop a 🙋 if you\'re excited!',
    postedAt: new Date('2025-03-15T11:00:00'),
    likes: 1567,
    shares: 412,
    comments: 523,
    engagement: 22.1,
  },
  {
    id: 'post6',
    accountId: 'sm4',
    platform: 'TikTok',
    content: 'POV: You\'re about to witness the launch of the year 👀 #FYP #ProductLaunch',
    mediaUrls: ['https://picsum.photos/seed/tiktok1/720/1280'],
    postedAt: new Date('2025-03-15T18:00:00'),
    likes: 45678,
    shares: 3421,
    comments: 1876,
    engagement: 35.4,
  },
];

// Mock Media Files
export const mockMediaFiles: MediaFile[] = [
  {
    id: 'mf1',
    filename: 'teaser_video_final.mp4',
    originalName: 'teaser_video_v3_edited.mp4',
    mimeType: 'video/mp4',
    size: 52428800,
    url: 'https://storage.example.com/media/teaser_video_final.mp4',
    thumbnailUrl: 'https://storage.example.com/thumbnails/teaser_video_thumb.jpg',
    uploadedBy: '2',
    campaignId: 'c1',
    tags: ['teaser', 'video', 'launch'],
    createdAt: new Date('2025-03-02'),
  },
  {
    id: 'mf2',
    filename: 'product_hero_image.png',
    originalName: 'hero_shot_retouched.png',
    mimeType: 'image/png',
    size: 8388608,
    url: 'https://storage.example.com/media/product_hero_image.png',
    thumbnailUrl: 'https://storage.example.com/thumbnails/product_hero_thumb.jpg',
    uploadedBy: '2',
    campaignId: 'c1',
    tags: ['product', 'hero', 'image'],
    createdAt: new Date('2025-03-05'),
  },
  {
    id: 'mf3',
    filename: 'brand_guidelines_2025.pdf',
    originalName: 'Brand_Guidelines_v2.3.pdf',
    mimeType: 'application/pdf',
    size: 15728640,
    url: 'https://storage.example.com/media/brand_guidelines_2025.pdf',
    uploadedBy: '1',
    campaignId: 'c1',
    tags: ['guidelines', 'brand', 'documentation'],
    createdAt: new Date('2025-02-15'),
  },
  {
    id: 'mf4',
    filename: 'social_templates.zip',
    originalName: 'instagram_linkedin_templates.zip',
    mimeType: 'application/zip',
    size: 31457280,
    url: 'https://storage.example.com/media/social_templates.zip',
    uploadedBy: '2',
    campaignId: 'c3',
    tags: ['templates', 'social', 'design'],
    createdAt: new Date('2025-04-02'),
  },
];

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: 'a1',
    name: 'Content Generator',
    type: 'llm-writer',
    description: 'AI agent for generating social media content and copy',
    isActive: true,
    capabilities: ['content-writing', 'hashtag-generation', 'tone-adjustment'],
    configuration: {
      model: 'gpt-4',
      temperature: 0.7,
      maxTokens: 500,
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'a2',
    name: 'Analytics Reporter',
    type: 'data-analyzer',
    description: 'AI agent for analyzing social media metrics and generating reports',
    isActive: true,
    capabilities: ['data-analysis', 'report-generation', 'trend-detection'],
    configuration: {
      model: 'claude-3',
      temperature: 0.3,
      maxTokens: 2000,
    },
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'a3',
    name: 'Engagement Bot',
    type: 'interaction-manager',
    description: 'AI agent for managing comments and engagement',
    isActive: false,
    capabilities: ['comment-response', 'sentiment-analysis', 'priority-flagging'],
    configuration: {
      model: 'gpt-4-turbo',
      temperature: 0.5,
      maxTokens: 300,
    },
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date(),
  },
];

// Mock Workflows
export const mockWorkflows: Workflow[] = [
  {
    id: 'w1',
    name: 'Daily Content Posting',
    description: 'Automated workflow for daily social media content posting',
    steps: [
      {
        id: 'ws1',
        order: 1,
        action: 'fetch-scheduled-content',
        parameters: { timeWindow: '24h' },
      },
      {
        id: 'ws2',
        order: 2,
        action: 'generate-hashtags',
        agentId: 'a1',
        parameters: { count: 10, style: 'trending' },
      },
      {
        id: 'ws3',
        order: 3,
        action: 'publish-to-platforms',
        parameters: { platforms: ['instagram', 'twitter', 'linkedin'] },
      },
    ],
    triggerType: 'scheduled',
    schedule: '0 9 * * *', // Daily at 9 AM
    isActive: true,
    campaignId: 'c1',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'w2',
    name: 'Weekly Analytics Report',
    description: 'Generate and distribute weekly performance reports',
    steps: [
      {
        id: 'ws4',
        order: 1,
        action: 'collect-metrics',
        parameters: { period: '7d', metrics: ['engagement', 'reach', 'followers'] },
      },
      {
        id: 'ws5',
        order: 2,
        action: 'analyze-trends',
        agentId: 'a2',
        parameters: { compareWith: 'previous_period' },
      },
      {
        id: 'ws6',
        order: 3,
        action: 'generate-report',
        agentId: 'a2',
        parameters: { format: 'pdf', includeCharts: true },
      },
      {
        id: 'ws7',
        order: 4,
        action: 'send-email',
        parameters: { recipients: ['team@brand.com'] },
      },
    ],
    triggerType: 'scheduled',
    schedule: '0 8 * * 1', // Every Monday at 8 AM
    isActive: true,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date(),
  },
  {
    id: 'w3',
    name: 'Crisis Response Protocol',
    description: 'Automated response workflow for negative sentiment detection',
    steps: [
      {
        id: 'ws8',
        order: 1,
        action: 'monitor-sentiment',
        parameters: { threshold: -0.5, keywords: ['complaint', 'issue', 'problem'] },
      },
      {
        id: 'ws9',
        order: 2,
        action: 'alert-team',
        condition: 'sentiment < -0.7',
        parameters: { urgency: 'high' },
      },
      {
        id: 'ws10',
        order: 3,
        action: 'draft-response',
        agentId: 'a1',
        condition: 'sentiment < -0.5',
        parameters: { tone: 'empathetic', escalate: true },
      },
    ],
    triggerType: 'event',
    isActive: true,
    campaignId: 'c1',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date(),
  },
];

// Mock Participants
export const mockParticipants: Participant[] = [
  {
    id: 'part1',
    userId: '1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'Campaign Manager',
    campaignIds: ['c1', 'c2', 'c3'],
    avatar: 'https://i.pravatar.cc/150?u=admin',
  },
  {
    id: 'part2',
    userId: '2',
    name: 'Worker User',
    email: 'worker@example.com',
    role: 'Content Creator',
    campaignIds: ['c1', 'c3'],
    avatar: 'https://i.pravatar.cc/150?u=worker',
  },
  {
    id: 'part3',
    agentId: 'a1',
    name: 'Content Generator',
    role: 'AI Copywriter',
    campaignIds: ['c1', 'c2', 'c3'],
  },
  {
    id: 'part4',
    agentId: 'a2',
    name: 'Analytics Reporter',
    role: 'Data Analyst',
    campaignIds: ['c1', 'c3'],
  },
];

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg1',
    senderId: '1',
    senderName: 'Admin User',
    content: 'Welcome to the Spring Launch campaign! Let\'s make this our best launch yet.',
    timestamp: new Date('2025-03-01T09:00:00'),
    isSystem: true,
  },
  {
    id: 'msg2',
    senderId: '2',
    senderName: 'Worker User',
    content: 'Excited to get started! The teaser video is ready for review.',
    timestamp: new Date('2025-03-01T09:15:00'),
  },
  {
    id: 'msg3',
    senderId: 'a1',
    senderName: 'Content Generator',
    content: 'I\'ve prepared 5 variations of launch day posts. Would you like to see them?',
    timestamp: new Date('2025-03-10T14:00:00'),
  },
  {
    id: 'msg4',
    senderId: '2',
    senderName: 'Worker User',
    content: 'Yes please! Share them in the media library.',
    timestamp: new Date('2025-03-10T14:05:00'),
  },
];

// Mock Credentials
export const mockCredentials: Credential[] = [
  {
    id: 'cred1',
    userId: '2',
    service: 'Canva Pro',
    username: 'designer@brand.com',
    notes: 'Team account - shared access',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: 'cred2',
    userId: '2',
    service: 'Adobe Creative Cloud',
    username: 'creative@brand.com',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'cred3',
    userId: '1',
    service: 'Google Analytics',
    username: 'analytics@brand.com',
    notes: 'Master account for all properties',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2025-02-15'),
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalCampaigns: 3,
  activeCampaigns: 2,
  totalTasks: 7,
  tasksByStatus: {
    planned: 2,
    in_progress: 2,
    blocker: 1,
    finished: 2,
  },
  totalPosts: 6,
  totalEngagement: 102.8,
  upcomingDeadlines: mockWorkPackages.filter(wp => wp.dueDate && new Date(wp.dueDate) > new Date()).slice(0, 5),
};

// Export all mock data as a single object for easy import
export const mockData = {
  users: mockUsers,
  campaigns: mockCampaigns,
  phases: mockPhases,
  milestones: mockMilestones,
  workPackages: mockWorkPackages,
  socialMediaAccounts: mockSocialMediaAccounts,
  socialMediaPosts: mockSocialMediaPosts,
  mediaFiles: mockMediaFiles,
  agents: mockAgents,
  workflows: mockWorkflows,
  participants: mockParticipants,
  chatMessages: mockChatMessages,
  credentials: mockCredentials,
  dashboardStats: mockDashboardStats,
};
